"use client";
import { useEffect, useMemo, useState } from "react";
import { AppState, Employee, buildDefaultState, getPhase, loadState, saveState } from "../lib/demo-data";
type Tab="overview"|"campaign"|"employees"|"catalog"|"purchase"|"history";
const labels:Record<Tab,string>={overview:"總覽",campaign:"本期設定",employees:"員工名單",catalog:"商品資料庫",purchase:"採購清單",history:"歷史紀錄"};

export default function AdminPage(){
 const [state,setState]=useState<AppState>(()=>buildDefaultState()); const [ready,setReady]=useState(false); const [tab,setTab]=useState<Tab>("overview");
 const [saved,setSaved]=useState(false); const [newName,setNewName]=useState(""); const [newEmail,setNewEmail]=useState("");
 useEffect(()=>{setState(loadState());setReady(true)},[]);
 function commit(next:AppState){setState(next);saveState(next);setSaved(true);window.setTimeout(()=>setSaved(false),1500)}
 const phase=getPhase(state.campaign);
 const candidates=useMemo(()=>state.products.filter(p=>state.nominations.some(n=>n.productId===p.id)),[state]);
 const ranking=useMemo(()=>candidates.map(p=>({...p,votes:state.votes.filter(v=>v.productId===p.id).length})).sort((a,b)=>b.votes-a.votes||a.price-b.price),[state,candidates]);
 const plan=useMemo(()=>{let remaining=state.campaign.budget;const rows=ranking.map(p=>({...p,quantity:0,subtotal:0}));rows.forEach(r=>{if(r.price<=remaining){r.quantity=1;r.subtotal=r.price;remaining-=r.price}});let i=0,guard=0;while(rows.length&&remaining>=Math.min(...rows.map(r=>r.price))&&guard<200){const r=rows[i%rows.length];if(r.price<=remaining){r.quantity++;r.subtotal+=r.price;remaining-=r.price}i++;guard++}return{rows:rows.filter(r=>r.quantity),total:state.campaign.budget-remaining,remaining}},[ranking,state.campaign.budget]);
 function update(key:keyof AppState["campaign"],value:string|number){commit({...state,campaign:{...state.campaign,[key]:value}})}
 function addEmployee(){const email=newEmail.trim().toLowerCase();if(!newName.trim()||!email||state.employees.some(e=>e.email.toLowerCase()===email))return;const employee:Employee={id:crypto.randomUUID(),name:newName.trim(),email,active:true,role:"employee"};commit({...state,employees:[...state.employees,employee]});setNewName("");setNewEmail("")}
 if(!ready)return <main className="loading-screen">載入管理後台…</main>;
 return <main className="admin-shell">
  <aside className="admin-nav"><div className="brand admin-brand"><span className="brand-mark">S</span><div><strong>Snack Vote</strong><small>管理後台</small></div></div><nav>{(Object.keys(labels) as Tab[]).map((item,index)=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}><span>{["⌂","◷","♙","▦","✓","↺"][index]}</span>{labels[item]}</button>)}</nav><div className="admin-user"><span className="avatar">張</span><div><strong>張婉如</strong><small>系統管理者</small></div></div></aside>
  <section className="admin-main"><header className="admin-top"><div><p className="section-kicker">ADMIN CONSOLE</p><h1>{labels[tab]}</h1></div><div className="admin-status"><span className={"status-pill "+phase}>{phase==="upcoming"?"尚未開始":phase==="nomination"?"提名階段":phase==="voting"?"投票階段":phase==="results"?"結果揭曉":"安排採購"}</span><span>{state.campaign.monthLabel}</span></div></header>
  <div className="prototype-note"><strong>目前為互動原型</strong><span>員工端與後台已分離；正式上線時，後台網址仍會在伺服器端驗證管理者權限。</span></div>

  {tab==="overview"&&<div className="admin-content"><div className="stat-grid"><article><span>啟用員工</span><strong>{state.employees.filter(e=>e.active).length}</strong><small>人</small></article><article><span>本期候選</span><strong>{candidates.length}</strong><small>項商品</small></article><article><span>已投票數</span><strong>{state.votes.length}</strong><small>票</small></article><article><span>本月預算</span><strong>{"$"}{state.campaign.budget.toLocaleString()}</strong><small>元</small></article></div><div className="admin-two">
   <section className="admin-card"><div className="card-title"><div><p className="section-kicker">LIVE RANKING</p><h2>目前排行</h2></div><button onClick={()=>setTab("purchase")}>查看採購試算</button></div><div className="ranking-list">{ranking.slice(0,5).map((item,index)=><div key={item.id}><b>{index+1}</b><span><strong>{item.name}</strong><small>{item.brand} · {item.size}</small></span><em>{item.votes} 票</em></div>)}{!ranking.length&&<div className="admin-empty">還沒有候選商品</div>}</div></section>
   <section className="admin-card"><div className="card-title"><div><p className="section-kicker">SCHEDULE</p><h2>四個時間節點</h2></div><button onClick={()=>setTab("campaign")}>調整</button></div><div className="schedule-list">{[["開始",state.campaign.startDate],["提名截止",state.campaign.nominationDeadline],["投票截止",state.campaign.votingDeadline],["安排採購",state.campaign.purchaseDate]].map((row,index)=><div key={row[0]}><i>{index+1}</i><span><strong>{row[0]}</strong><small>{row[1]} · 09:00</small></span></div>)}</div></section>
  </div><section className="admin-card mail-card"><div><p className="section-kicker">EMAIL DELIVERY</p><h2>階段通知信</h2><p>啟用名單共 {state.employees.filter(e=>e.active).length} 人。正式寄送服務尚未設定，因此目前不會顯示可寄送的假按鈕。</p></div><div className="mail-state"><span>尚未連接</span><small>設定郵件服務後才會開放測試寄送與排程</small></div></section></div>}

  {tab==="campaign"&&<div className="admin-content"><section className="admin-card form-card"><div className="card-title"><div><p className="section-kicker">MONTHLY CAMPAIGN</p><h2>本期規則與日期</h2></div>{saved&&<span className="saved-hint">✓ 已儲存</span>}</div><div className="form-grid">
   <label><span>月份名稱</span><input value={state.campaign.monthLabel} onChange={e=>update("monthLabel",e.target.value)}/></label><label><span>本月預算</span><div className="input-prefix"><i>$</i><input type="number" min="0" value={state.campaign.budget} onChange={e=>update("budget",Math.max(0,Number(e.target.value)))}/></div></label>
   <label><span>每人提名上限</span><select value={state.campaign.nominationLimit} onChange={e=>update("nominationLimit",Math.min(Number(e.target.value),state.campaign.voteLimit))}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select><small>提名會固定占用同等票數</small></label><label><span>每人總票數</span><select value={state.campaign.voteLimit} onChange={e=>update("voteLimit",Math.max(Number(e.target.value),state.campaign.nominationLimit))}>{[2,3,4,5,6,8].map(n=><option key={n}>{n}</option>)}</select><small>預設 4 票，含提名票</small></label>
   <label><span>開始</span><input type="date" value={state.campaign.startDate} onChange={e=>update("startDate",e.target.value)}/><small>開始開放同仁提名</small></label><label><span>提名截止</span><input type="date" value={state.campaign.nominationDeadline} onChange={e=>update("nominationDeadline",e.target.value)}/><small>截止後進入投票階段</small></label><label><span>投票截止</span><input type="date" value={state.campaign.votingDeadline} onChange={e=>update("votingDeadline",e.target.value)}/><small>截止後鎖定票數並揭曉結果</small></label><label><span>安排採購</span><input type="date" value={state.campaign.purchaseDate} onChange={e=>update("purchaseDate",e.target.value)}/><small>結果揭曉期結束並安排採購</small></label>
  </div><div className="rule-note"><strong>三段期間</strong><span>提名階段＝開始至提名截止；投票階段＝提名截止至投票截止；結果揭曉階段＝投票截止至安排採購。正式版會強制檢查四個日期依序排列。</span></div></section></div>}

  {tab==="employees"&&<div className="admin-content"><section className="admin-card"><div className="card-title"><div><p className="section-kicker">EMPLOYEE ROSTER</p><h2>員工名單</h2></div><span className="count-tag">{state.employees.length} 人</span></div><div className="add-employee"><input placeholder="姓名" value={newName} onChange={e=>setNewName(e.target.value)}/><input type="email" placeholder="Email" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><button onClick={addEmployee}>＋ 新增員工</button></div><div className="table-wrap"><table><thead><tr><th>姓名</th><th>Email</th><th>權限</th><th>狀態</th><th></th></tr></thead><tbody>{state.employees.map(employee=><tr key={employee.id}><td><strong>{employee.name}</strong></td><td>{employee.email}</td><td>{employee.role==="admin"?"管理者":"員工"}</td><td><span className={employee.active?"active-dot":"inactive-dot"}>{employee.active?"啟用":"停用"}</span></td><td><button className="table-action" onClick={()=>commit({...state,employees:state.employees.map(e=>e.id===employee.id?{...e,active:!e.active}:e)})}>{employee.active?"停用":"恢復"}</button></td></tr>)}</tbody></table></div></section></div>}

  {tab==="catalog"&&<div className="admin-content"><section className="admin-card"><div className="card-title"><div><p className="section-kicker">PRODUCT CATALOG</p><h2>零食資料庫</h2></div><span className="count-tag">{state.products.filter(p=>p.active).length} 項啟用</span></div><div className="catalog-admin">{state.products.map(product=><div key={product.id}><span className={"catalog-swatch tone-"+product.tone}>{product.category.slice(0,1)}</span><span><strong>{product.name}</strong><small>{product.brand} · {product.category} · {product.size}</small></span><em>{"$"}{product.price}</em><button onClick={()=>commit({...state,products:state.products.map(p=>p.id===product.id?{...p,active:!p.active}:p)})}>{product.active?"啟用":"停用"}</button></div>)}</div><div className="rule-note"><strong>正式商品庫</strong><span>將支援 CSV 批次匯入、分類、品牌、規格、參考價與停用品項；價格不宣稱為門市即時售價。</span></div></section></div>}

  {tab==="purchase"&&<div className="admin-content"><div className="purchase-summary"><div><span>本月預算</span><strong>{"$"}{state.campaign.budget.toLocaleString()}</strong></div><div><span>建議採購</span><strong>{"$"}{plan.total.toLocaleString()}</strong></div><div><span>預算餘額</span><strong>{"$"}{plan.remaining.toLocaleString()}</strong></div></div><section className="admin-card"><div className="card-title"><div><p className="section-kicker">BUDGET PLAN</p><h2>依排名產生的建議清單</h2></div><span className="count-tag">{plan.rows.length} 項</span></div><div className="table-wrap"><table><thead><tr><th>排名</th><th>商品</th><th>票數</th><th>參考單價</th><th>建議數量</th><th>小計</th></tr></thead><tbody>{plan.rows.map((row,index)=><tr key={row.id}><td>#{index+1}</td><td><strong>{row.name}</strong><small className="cell-sub">{row.brand} · {row.size}</small></td><td>{row.votes}</td><td>{"$"}{row.price}</td><td>{row.quantity}</td><td><strong>{"$"}{row.subtotal}</strong></td></tr>)}</tbody></table></div><div className="rule-note"><strong>試算原則</strong><span>先依票數排名讓入選商品各取得基本數量，再把剩餘預算由高排名往下分配；最終仍由採購者依門市實價與庫存確認。</span></div></section></div>}

  {tab==="history"&&<div className="admin-content"><div className="history-grid">{state.history.map(item=><article className="admin-card history-admin" key={item.month}><span>已封存</span><h2>{item.month}</h2><p>{item.winners.join("、")}</p><div><strong>{"$"}{item.actualCost.toLocaleString()}</strong><small>{item.voterCount} 人 · {item.voteCount} 票</small></div></article>)}</div></div>}
  </section>
 </main>
}
